/* Generated By:JavaCC: Do not edit this line. MazeParserConstants.java */
package org.maze.core.io;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MazeParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SIZE = 5;
  /** RegularExpression Id. */
  int START = 6;
  /** RegularExpression Id. */
  int GOAL = 7;
  /** RegularExpression Id. */
  int ITEM = 8;
  /** RegularExpression Id. */
  int OBSTACLE = 9;
  /** RegularExpression Id. */
  int SCRIPT = 10;
  /** RegularExpression Id. */
  int PLUGIN = 11;
  /** RegularExpression Id. */
  int AT = 12;
  /** RegularExpression Id. */
  int REQUIRES = 13;
  /** RegularExpression Id. */
  int MESSAGE = 14;
  /** RegularExpression Id. */
  int LPAREN = 15;
  /** RegularExpression Id. */
  int RPAREN = 16;
  /** RegularExpression Id. */
  int LBRACE = 17;
  /** RegularExpression Id. */
  int RBRACE = 18;
  /** RegularExpression Id. */
  int COMMA = 19;
  /** RegularExpression Id. */
  int NUMBER = 20;
  /** RegularExpression Id. */
  int IDENTIFIER = 21;
  /** RegularExpression Id. */
  int QUOTED_STRING = 22;
  /** RegularExpression Id. */
  int SCRIPT_CONTENT = 23;
  /** RegularExpression Id. */
  int UNEXPECTED = 25;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SCRIPT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"size\"",
    "\"start\"",
    "\"goal\"",
    "\"item\"",
    "\"obstacle\"",
    "\"script\"",
    "\"plugin\"",
    "\"at\"",
    "\"requires\"",
    "\"message\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "<NUMBER>",
    "<IDENTIFIER>",
    "<QUOTED_STRING>",
    "<SCRIPT_CONTENT>",
    "\"}\"",
    "<UNEXPECTED>",
  };

}
