/* Generated By:JavaCC: Do not edit this line. MazeParserConstants.java */
package org.maze.core.io;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MazeParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SIZE = 5;
  /** RegularExpression Id. */
  int START = 6;
  /** RegularExpression Id. */
  int GOAL = 7;
  /** RegularExpression Id. */
  int ITEM = 8;
  /** RegularExpression Id. */
  int OBSTACLE = 9;
  /** RegularExpression Id. */
  int COLON = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int NUMBER = 12;
  /** RegularExpression Id. */
  int IDENTIFIER = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"size\"",
    "\"start\"",
    "\"goal\"",
    "\"item\"",
    "\"obstacle\"",
    "\":\"",
    "\",\"",
    "<NUMBER>",
    "<IDENTIFIER>",
  };

}
